import { BiodataSection } from "@/types/biodata";

/**
 * Default biodata sections and fields for Indian Wedding Biodata
 */

export const DEFAULT_SECTIONS: BiodataSection[] = [
  {
    id: "personal",
    title: "Personal Details",
    titleHindi: "व्यक्तिगत विवरण",
    icon: "User",
    order: 0,
    visible: true,
    collapsible: true,
    collapsed: false,
    fields: [
      {
        id: "name",
        label: "Full Name",
        labelHindi: "पूरा नाम",
        type: "text",
        value: "",
        placeholder: "Enter full name",
        order: 0,
        visible: true,
        editable: true,
        validation: {
          minLength: 2,
          maxLength: 100,
          message: "Name must be between 2 and 100 characters",
        },
      },
      {
        id: "dateOfBirth",
        label: "Date of Birth",
        labelHindi: "जन्म तिथि",
        type: "date",
        value: "",
        order: 1,
        visible: true,
        editable: true,
      },
      {
        id: "timeOfBirth",
        label: "Time of Birth",
        labelHindi: "जन्म समय",
        type: "time",
        value: "",
        order: 2,
        visible: false,
        editable: true,
      },
      {
        id: "placeOfBirth",
        label: "Place of Birth",
        labelHindi: "जन्म स्थान",
        type: "text",
        value: "",
        placeholder: "City, State",
        order: 3,
        visible: false,
        editable: true,
      },
      {
        id: "height",
        label: "Height",
        labelHindi: "ऊंचाई",
        type: "text",
        value: "",
        placeholder: "e.g., 5'8\" or 173 cm",
        order: 4,
        visible: true,
        editable: true,
      },
      {
        id: "complexion",
        label: "Complexion",
        labelHindi: "रंग",
        type: "select",
        value: "",
        options: ["Fair", "Wheatish", "Dusky", "Dark"],
        order: 5,
        visible: false,
        editable: true,
      },
      {
        id: "bloodGroup",
        label: "Blood Group",
        labelHindi: "रक्त समूह",
        type: "select",
        value: "",
        options: ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"],
        order: 6,
        visible: false,
        editable: true,
      },
      {
        id: "maritalStatus",
        label: "Marital Status",
        labelHindi: "वैवाहिक स्थिति",
        type: "select",
        value: "Never Married",
        options: ["Never Married", "Divorced", "Widowed", "Awaiting Divorce"],
        order: 7,
        visible: true,
        editable: true,
      },
      {
        id: "religion",
        label: "Religion",
        labelHindi: "धर्म",
        type: "text",
        value: "",
        placeholder: "e.g., Hindu",
        order: 8,
        visible: true,
        editable: true,
      },
      {
        id: "caste",
        label: "Caste",
        labelHindi: "जाति",
        type: "text",
        value: "",
        placeholder: "e.g., Brahmin",
        order: 9,
        visible: true,
        editable: true,
      },
      {
        id: "subcaste",
        label: "Sub-caste / Gotra",
        labelHindi: "उपजाति / गोत्र",
        type: "text",
        value: "",
        placeholder: "e.g., Gotra name",
        order: 10,
        visible: false,
        editable: true,
      },
      {
        id: "motherTongue",
        label: "Mother Tongue",
        labelHindi: "मातृभाषा",
        type: "text",
        value: "",
        placeholder: "e.g., Hindi, Tamil",
        order: 11,
        visible: true,
        editable: true,
      },
      {
        id: "diet",
        label: "Diet",
        labelHindi: "आहार",
        type: "select",
        value: "",
        options: ["Vegetarian", "Non-Vegetarian", "Eggetarian", "Vegan", "Jain"],
        order: 12,
        visible: true,
        editable: true,
      },
      {
        id: "hobbies",
        label: "Hobbies & Interests",
        labelHindi: "शौक और रुचियाँ",
        type: "textarea",
        value: "",
        placeholder: "Reading, travelling, cooking...",
        order: 13,
        visible: false,
        editable: true,
      },
    ],
  },
  {
    id: "education",
    title: "Education & Career",
    titleHindi: "शिक्षा और करियर",
    icon: "GraduationCap",
    order: 1,
    visible: true,
    collapsible: true,
    collapsed: false,
    fields: [
      {
        id: "highestQualification",
        label: "Highest Qualification",
        labelHindi: "उच्चतम शिक्षा",
        type: "text",
        value: "",
        placeholder: "e.g., B.Tech, MBA, MBBS",
        order: 0,
        visible: true,
        editable: true,
      },
      {
        id: "university",
        label: "University / College",
        labelHindi: "विश्वविद्यालय / कॉलेज",
        type: "text",
        value: "",
        placeholder: "Name of institution",
        order: 1,
        visible: false,
        editable: true,
      },
      {
        id: "additionalQualification",
        label: "Additional Qualifications",
        labelHindi: "अतिरिक्त योग्यता",
        type: "textarea",
        value: "",
        placeholder: "Any certifications, courses...",
        order: 2,
        visible: false,
        editable: true,
      },
      {
        id: "occupation",
        label: "Occupation",
        labelHindi: "व्यवसाय",
        type: "text",
        value: "",
        placeholder: "e.g., Software Engineer, Doctor",
        order: 3,
        visible: true,
        editable: true,
      },
      {
        id: "employedIn",
        label: "Employed In",
        labelHindi: "कार्यरत",
        type: "select",
        value: "",
        options: [
          "Private Sector",
          "Government / PSU",
          "Business / Self-Employed",
          "Defence / Civil Services",
          "Not Working",
          "Student",
        ],
        order: 4,
        visible: true,
        editable: true,
      },
      {
        id: "companyName",
        label: "Company / Organization",
        labelHindi: "कंपनी / संगठन",
        type: "text",
        value: "",
        placeholder: "Name of employer",
        order: 5,
        visible: false,
        editable: true,
      },
      {
        id: "workLocation",
        label: "Work Location",
        labelHindi: "कार्य स्थान",
        type: "text",
        value: "",
        placeholder: "City, Country",
        order: 6,
        visible: true,
        editable: true,
      },
      {
        id: "annualIncome",
        label: "Annual Income",
        labelHindi: "वार्षिक आय",
        type: "text",
        value: "",
        placeholder: "e.g., 10-15 LPA or Not Disclosed",
        order: 7,
        visible: true,
        editable: true,
      },
    ],
  },
  {
    id: "family",
    title: "Family Details",
    titleHindi: "पारिवारिक विवरण",
    icon: "Users",
    order: 2,
    visible: true,
    collapsible: true,
    collapsed: false,
    fields: [
      {
        id: "fatherName",
        label: "Father's Name",
        labelHindi: "पिता का नाम",
        type: "text",
        value: "",
        placeholder: "Full name",
        order: 0,
        visible: true,
        editable: true,
      },
      {
        id: "fatherOccupation",
        label: "Father's Occupation",
        labelHindi: "पिता का व्यवसाय",
        type: "text",
        value: "",
        placeholder: "e.g., Businessman, Retired",
        order: 1,
        visible: false,
        editable: true,
      },
      {
        id: "motherName",
        label: "Mother's Name",
        labelHindi: "माता का नाम",
        type: "text",
        value: "",
        placeholder: "Full name",
        order: 2,
        visible: true,
        editable: true,
      },
      {
        id: "motherOccupation",
        label: "Mother's Occupation",
        labelHindi: "माता का व्यवसाय",
        type: "text",
        value: "",
        placeholder: "e.g., Homemaker, Teacher",
        order: 3,
        visible: false,
        editable: true,
      },
      {
        id: "siblings",
        label: "Siblings",
        labelHindi: "भाई-बहन",
        type: "textarea",
        value: "",
        placeholder: "e.g., 1 Elder Brother (Married, Engineer), 1 Younger Sister (Student)",
        order: 4,
        visible: true,
        editable: true,
      },
      {
        id: "familyType",
        label: "Family Type",
        labelHindi: "परिवार का प्रकार",
        type: "select",
        value: "",
        options: ["Joint Family", "Nuclear Family"],
        order: 5,
        visible: true,
        editable: true,
      },
      {
        id: "familyStatus",
        label: "Family Status",
        labelHindi: "पारिवारिक स्थिति",
        type: "select",
        value: "",
        options: ["Middle Class", "Upper Middle Class", "Rich / Affluent"],
        order: 6,
        visible: true,
        editable: true,
      },
      {
        id: "familyValues",
        label: "Family Values",
        labelHindi: "पारिवारिक मूल्य",
        type: "select",
        value: "",
        options: ["Traditional", "Moderate", "Liberal"],
        order: 7,
        visible: true,
        editable: true,
      },
      {
        id: "nativePlace",
        label: "Native Place",
        labelHindi: "मूल स्थान",
        type: "text",
        value: "",
        placeholder: "Ancestral hometown",
        order: 8,
        visible: true,
        editable: true,
      },
      {
        id: "familyAbout",
        label: "About Family",
        labelHindi: "परिवार के बारे में",
        type: "textarea",
        value: "",
        placeholder: "Brief description of family background...",
        order: 9,
        visible: false,
        editable: true,
      },
    ],
  },
  {
    id: "astro",
    title: "Horoscope Details",
    titleHindi: "कुंडली विवरण",
    icon: "Star",
    order: 3,
    visible: true,
    collapsible: true,
    collapsed: true,
    fields: [
      {
        id: "rashi",
        label: "Rashi (Moon Sign)",
        labelHindi: "राशि",
        type: "select",
        value: "",
        options: [
          "Mesh (Aries)",
          "Vrishabh (Taurus)",
          "Mithun (Gemini)",
          "Kark (Cancer)",
          "Singh (Leo)",
          "Kanya (Virgo)",
          "Tula (Libra)",
          "Vrishchik (Scorpio)",
          "Dhanu (Sagittarius)",
          "Makar (Capricorn)",
          "Kumbh (Aquarius)",
          "Meen (Pisces)",
        ],
        order: 0,
        visible: true,
        editable: true,
      },
      {
        id: "nakshatra",
        label: "Nakshatra",
        labelHindi: "नक्षत्र",
        type: "text",
        value: "",
        placeholder: "e.g., Rohini",
        order: 1,
        visible: true,
        editable: true,
      },
      {
        id: "manglik",
        label: "Manglik Status",
        labelHindi: "मांगलिक स्थिति",
        type: "select",
        value: "",
        options: ["Yes", "No", "Partial / Anshik", "Don't Know"],
        order: 2,
        visible: true,
        editable: true,
      },
      {
        id: "charan",
        label: "Charan / Pada",
        labelHindi: "चरण",
        type: "select",
        value: "",
        options: ["1", "2", "3", "4"],
        order: 3,
        visible: true,
        editable: true,
      },
      {
        id: "gan",
        label: "Gan",
        labelHindi: "गण",
        type: "select",
        value: "",
        options: ["Dev", "Manushya", "Rakshas"],
        order: 4,
        visible: true,
        editable: true,
      },
      {
        id: "nadi",
        label: "Nadi",
        labelHindi: "नाड़ी",
        type: "select",
        value: "",
        options: ["Aadi (Vaat)", "Madhya (Pitta)", "Antya (Kapha)"],
        order: 5,
        visible: true,
        editable: true,
      },
    ],
  },
  {
    id: "contact",
    title: "Contact Details",
    titleHindi: "संपर्क विवरण",
    icon: "Phone",
    order: 4,
    visible: true,
    collapsible: true,
    collapsed: false,
    fields: [
      {
        id: "address",
        label: "Residential Address",
        labelHindi: "पता",
        type: "textarea",
        value: "",
        placeholder: "Full address",
        order: 0,
        visible: true,
        editable: true,
      },
      {
        id: "city",
        label: "City",
        labelHindi: "शहर",
        type: "text",
        value: "",
        placeholder: "Current city",
        order: 1,
        visible: true,
        editable: true,
      },
      {
        id: "state",
        label: "State",
        labelHindi: "राज्य",
        type: "text",
        value: "",
        placeholder: "State",
        order: 2,
        visible: false,
        editable: true,
      },
      {
        id: "country",
        label: "Country",
        labelHindi: "देश",
        type: "text",
        value: "India",
        placeholder: "Country",
        order: 3,
        visible: false,
        editable: true,
      },
      {
        id: "phone",
        label: "Phone Number",
        labelHindi: "फ़ोन नंबर",
        type: "phone",
        value: "",
        placeholder: "+91 XXXXX XXXXX",
        order: 4,
        visible: true,
        editable: true,
      },
      {
        id: "email",
        label: "Email Address",
        labelHindi: "ईमेल",
        type: "email",
        value: "",
        placeholder: "email@example.com",
        order: 5,
        visible: true,
        editable: true,
      },
    ],
  },
  {
    id: "expectations",
    title: "Partner Preferences",
    titleHindi: "जीवनसाथी की अपेक्षाएं",
    icon: "Heart",
    order: 5,
    visible: true,
    collapsible: true,
    collapsed: true,
    fields: [
      {
        id: "partnerAge",
        label: "Preferred Age",
        labelHindi: "आयु सीमा",
        type: "text",
        value: "",
        placeholder: "e.g., 25-30 years",
        order: 0,
        visible: true,
        editable: true,
      },
      {
        id: "partnerHeight",
        label: "Preferred Height",
        labelHindi: "ऊंचाई",
        type: "text",
        value: "",
        placeholder: "e.g., 5'4\" and above",
        order: 1,
        visible: true,
        editable: true,
      },
      {
        id: "partnerEducation",
        label: "Preferred Education",
        labelHindi: "शिक्षा",
        type: "text",
        value: "",
        placeholder: "e.g., Graduate and above",
        order: 2,
        visible: true,
        editable: true,
      },
      {
        id: "partnerOccupation",
        label: "Preferred Occupation",
        labelHindi: "व्यवसाय",
        type: "text",
        value: "",
        placeholder: "e.g., Any professional job",
        order: 3,
        visible: true,
        editable: true,
      },
      {
        id: "partnerLocation",
        label: "Preferred Location",
        labelHindi: "स्थान",
        type: "text",
        value: "",
        placeholder: "e.g., Same city or willing to relocate",
        order: 4,
        visible: true,
        editable: true,
      },
      {
        id: "otherExpectations",
        label: "Other Expectations",
        labelHindi: "अन्य अपेक्षाएं",
        type: "textarea",
        value: "",
        placeholder: "Any other preferences...",
        order: 5,
        visible: true,
        editable: true,
      },
    ],
  },
];

/**
 * Field type options for creating custom fields
 */
export const FIELD_TYPE_OPTIONS = [
  { value: "text", label: "Text" },
  { value: "textarea", label: "Long Text" },
  { value: "select", label: "Dropdown" },
  { value: "date", label: "Date" },
  { value: "time", label: "Time" },
  { value: "email", label: "Email" },
  { value: "phone", label: "Phone Number" },
  { value: "number", label: "Number" },
  { value: "url", label: "Website URL" },
] as const;

/**
 * Section icon options (Lucide icon names)
 */
export const SECTION_ICON_OPTIONS = [
  { value: "User", label: "Person" },
  { value: "Users", label: "Family" },
  { value: "GraduationCap", label: "Education" },
  { value: "Briefcase", label: "Work" },
  { value: "Star", label: "Star" },
  { value: "Heart", label: "Heart" },
  { value: "Phone", label: "Contact" },
  { value: "Home", label: "Home" },
  { value: "MapPin", label: "Location" },
  { value: "Info", label: "Info" },
] as const;
